global:

  scrape_interval: 30s

# Scrape a single endpoint:
scrape_configs:

  - job_name: 'pandora'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['host.docker.internal:8080']
